# Latihan Numpy

In [1]:
# import numpy
import numpy as np

In [4]:
# Perubahan dari List ke Array
# np.array

a = [1,2,3,4,5]
print(a)
print(type(a))

b = np.array(a)
print(b)
print(type(b))

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Membuat Array 2D
# Lihat seberapa banyak kurung siku diawal untuk menentukan jumlah dimensi
c = [[1,2,3],
     [3,4,5]]
c = np.array(c)
c


array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
# menetukan ukuran array
# .shape

print(c)
print(c.shape)

print(b)
print(b.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)
[1 2 3 4 5]
(5,)


In [9]:
# menentukan jumlah total elemen suatu array
#.size

print(b)
print(b.size)

print(c)
print(c.size)

[1 2 3 4 5]
5
[[1 2 3]
 [3 4 5]]
6


In [15]:
# indexing & slicing
print(b)
print(b[0:1])
print(b[:])
print(b[::2])
# mengubah urutan array 1D dari belakang ke depan (descending)
print(b[::-1])

[1 2 3 4 5]
[1]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


# Nomor 1

Buatlah sebuah array seperti dibawah ini dan tambhakan setiap elemennya dengan 1.

a = [10,20,30,40,50]

In [16]:
# cara 1
a = [10,20,30,40,50]

a = np.array(a)
a
print(a+1)

[11 21 31 41 51]


In [17]:
# cara 2


array([10, 20, 30, 40, 50])

In [24]:
c = np.array([10,-8,4,5,-41,7,5,-4])
np.sort(c[c>0]) [::-1]



array([10,  7,  5,  5,  4])

In [29]:
d = np.array([1,2,3,4,5])
e = np.array([6,7,8,9,10])

print(np.hstack((d, e)))
np.vstack((d, e))

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
f = np.array([10,20,30,40,50])
f2 = f.copy() * 2 
f3 = f.copy() * 3



In [46]:
print(f2)
print(f3)

[ 20  40  60  80 100]
[ 30  60  90 120 150]


In [70]:
k = np.array([[1,2,3],[4,5,6]])
print(k.min(axis=1))
print(k.min(axis=0))

print(k.max(axis=1))
print(k.max(axis=0))

print(k.sum(axis=1))
print(k.sum(axis=0))


[1 4]
[1 2 3]
[3 6]
[4 5 6]
[ 6 15]
[5 7 9]


In [98]:
min?

Docstring:
min(iterable, *[, default=obj, key=func]) -> value
min(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its smallest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the smallest argument.
Type:      builtin_function_or_method


In [73]:
l = np.array([[1,2,3],[4,5,6],[7,8,9]])
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
l[:,1]


array([2, 5, 8])

In [84]:
print(np.diag(l))
print(np.diag(np.diag(l)))

[1 5 9]
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [85]:
np.diag(np.fliplr(l))

array([3, 5, 7])

In [87]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2
1
